### ISSUE TITLE
{docs} ReadMe-00-Setting-Up.md : fields added in book seeder don't exist

### ISSUE THREAD

**Issue by Ateya9** [AdyGCode/ICT50120-SaaS-Library#2]
There is data trying to be inserted into 'height', 'genre' and 'sub_genre', but these rows aren't created in books migration, nor are they present in the book model.

They should be added on line 134 and 148.

**Comment by Ateya9** [comment]
these fields are also missing when creating the 'unknownBook' entry. These fields should be added as null on line 279.

**Comment by AdyGCode** [comment]
These are now added to the 00-Setting-Up document
