### ISSUE TITLE
{docs} ReadMe-11-API-index-show.md : typo ($author should be $authors)

### ISSUE THREAD

**Issue by Ateya9** [AdyGCode/ICT50120-SaaS-Library#3]
$author on line 109 should be $authors.

https://github.com/AdyGCode/ICT50120-SaaS-Library/blob/5370b7a17f09f0376e3e5d6108d8ea995c25bc51/_docs/ReadMe-11-API-index-show.md?plain=1#L109

**Comment by AdyGCode** [comment]
Fixed.
