### ISSUE TITLE
{docs} ReadMe-00-Setting-Up.md : Model for AuthorBook not needed + automatically pluralising

### ISSUE THREAD

**Issue by Ateya9** [AdyGCode/ICT50120-SaaS-Library#4]
Currently line 102 automatically puts an 's' on the end of the table it creates, causing the seeder to break. Also a model is not really needed for a pivot table. This line should probably be changed to something like:

`sail artisan make:migration create_author_book_table --create --table=author_book`

https://github.com/AdyGCode/ICT50120-SaaS-Library/blob/5370b7a17f09f0376e3e5d6108d8ea995c25bc51/_docs/ReadMe-00-Setting-Up.md?plain=1#L102

**Comment by AdyGCode** [comment]
changed the artisan call, and also added explanatory text.
